### ISSUE TITLE
缺少类  PswdInputView

### ISSUE THREAD

**Issue by wyy16318** [yilylong/TabIndicatorView#1]
import com.zhl.tabindicatorview.view.PswdInputView;

  <com.zhl.tabindicatorview.view.PswdItemView
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_gravity="center"
        android:layout_marginBottom="10dp"
        android:layout_marginTop="10dp"
        app:tab_position="0"
        app:tab_title="近三月" />

这个类找不到

**Comment by yilylong** [comment]
注释掉就可以运行了
